---
title: "Species ID Guide Template"
author: "Meredith Miller"
date: "10/18/2021"
output:
    pdf_document:
        includes:
            in_header: file.tex
---

\newpage

# *Calliostoma ligatum* (Blue top snail)

## Description

*Calliostoma ligatum*'s shells are cone-shaped with three distinct convex whorls, and are generally 2.5 to 3 cm in diameter and 1.7 to 3 cm tall (Tuskes 2019; Crowles 2004; Meschkat et al., 2013). ). The colour of their unbeaded spiral ridges generally alternates between light golden or tan and chocolate brown, although spirals can be white, grey, black or red. If the shell is worn or damaged a distinctive blue inner layer is visible, which can also be seen in the inner edge of empty shells. The shell has a closed umbilicus, and its opening is rounded with a pearly interior. The snail’s foot has a distinctive bright orange sole. 

*Calliostoma ligatum* is present from central Alaska to southern California (Metschkat et al., 2013; Harbo 2011). It can be found intertidally but also at depths of up to 30 meters in eel grass and kelp beds, and rocky areas. Blue top snails are omnivorous, and although they mainly consume *Macrocystis* and other brown algae they also eat diatoms, ascidians, sponges, bryozoans, and detritus (Crowles 2004; Meschkat et al., 2013). Their main predators are sea stars and sunflower stars, but, interestingly, they do not demonstrate antipredator behaviour towards predatory snails (Hoffman, 1980). As broadcast spawners, male *Calliostoma ligatum* release sperm into the water column, while eggs are released by females sheathed in mucous strands that await fertilization (Holyvoak 1988). After fertilization, they undergo several changes over 12 days to become planktonic larvae, veligers, and then juvenile snails. They reach sexual maturity after 1 year. Blue top snails may be confused for Purple-ringed top snails (*Calliostoma annulatum*), but the beaded spirals on Purple-ringed top snails are easily differentiated from the smooth spirals of Blue top snails. Other snails in the area either do not have a similar top-like shell morphology, or lack the distinguishable spirals and orange foot of the top snails. 

## Identification Questions

1) Is the shell of the snail top shaped (not cone shaped) with three convex whorls? 

2) Does the snail have a bright orange foot? 

3) Are the spiral ridges on the snail's shell smoothed (not beaded)? 

\newpage 

# *Nucella lamellosa* (Frilled/Wrinkled Dogwinkle)

## Description

*Nucella lamellosa’s* shell can have very variable characteristics, such as color and texture. Typically in solid colours, they can be light brown, grey, to white, but can also have banding patterns (Harbo, 2011). Some have even been observed in orange and purple colouring with coloured bands. Their ‘frilled’ name comes from their lamella, which look like wrinkles or ruffles in the whelk’s shell. A shell can have up to 12 lamellae (Proudfoot & Fretwell, 2015). Presence or absence of frills in this species has been observed to vary with both wave and predator (*Cancer productus*) exposure. Typically, wave exposed snails have smooth shells. Their shells are not ‘polished’ looking and are spirally coiled with 5-7 whorls (Bering et al. 2017). Overall, shell shape is elongated into a point and can reach up to 80mm in height (Proudfoot & Fretwell, 2015). The shell mouth opening is ovate and the lip of the shell is smooth and rounded with white coloring (or outside shell colour) on the inside (Bering et al. 2017). Its operculum is strongly spiraled and usually big enough to fully close the snail’s shell mouth opening, and it has a closed umbilicus (Bering et al. 2017). Color, texture, thickness, coloured banding, and sometimes shape can vary widely for this species (Proudfoot & Fretwell, 2015). As there are 4 Nucella species in BC, this snail is commonly mistaken for its relatives. Greyish or white *N. lamellosa* can look a lot like *Nucella canaliculata*, however *N. canaliculata* is typically more streamlined in shape and doesn't have any frills on its shell (Proudfoot & Fretwell, 2015). 

*N. lamellosa’s* range extends from Alaska (Aleutian Islands) to California (central) (Proudfoot & Fretwell, 2015; Harbo, 2011). This range suggests Frilled Dogwinkles can live in a breadth of conditions, but distributions suggest preference for cold temperate waters (Bering et al. 2017). In terms of habitat preferences, these snails inhabit the rocky intertidal, specifically mid to low zones but can be in shallow subtidal locations as well (Proudfoot & Fretwell, 2015; Harbo, 2011). The Frilled Dogwinkle inhabits rocky crevices, rock faces, as well as barnacle and mussel beds. Frilled Dogwinkles are predatory and feed on mussels and acorn barnacles (among other mollusks) by drilling into them with their radula and using a siphon that penetrates the prey’s shell to feed on internal tissues (Carefoot, 2021). Mating occurs in winter and spring. Sexually mature (>4yrs old) snails aggregate to breed with a group at their original hatching site (Bering et al. 2017). Females spawn eggs after 20 months and baby snails hatch from them after 140 days. Eggs are contained in capsules that protect them from factors such as salinity stress. Eggs (“sea oats”) are pale yellow and shaped like ~10mm vases, they can be observed on rocks in clusters (Bering et al. 2017). 

## Questions

1) Does the snail have 5-7 whorls, with the last whorl being the largest by far?

2) Does it have an oval aperture that is around half the length of the shell?

3) Is the lip thick, rounded, and smooth, with white or the shell’s outer color showing through?

\newpage

# *Tegula funebralis* (Black Tegula/Black Turban Snail)

## Description

The *Tegula funebralis* has a thick and strong cone-shaped shell with a closed umbilicus (Fretwell & Starzomski, 2013). The rounded shell consists of four whorls, and it can grow up to three centimeters in diameter (Harbo, 2011). When wet, the shell appears non-shiny and black, but when dry can have a more dark purple or grey tone (Fretwell & Starzomski, 2013). The tip of the shell gets worn down over time, revealing a pearly white surface. The white interior contains a black-bodied snail, and the bottom of the foot appears tan. Males have a paler foot than females. Other similar species include the brown turban snail (*Chlorostoma brunnea*), and the dusky turban snail (*Tegula pulligo*). Both of these species have a lighter brown shell than the black turban snail, and C. brunnea is not found north of Oregon state. 

The black turban snail is most commonly found along exposed or semi-protected rocky shorelines (Fretwell & Starzomski, 2013). It ranges along the west coast of North America from northern Vancouver Island down to central mexico. These snails can be found along the entire intertidal, but mainly live in the mid/low zones. Black turban snails live in large groups, usually aggregated under rocks. If shells are found isolated from other individuals, there is most likely a hermit crab or other invertebrate living in its shell. These grazing herbivores will eat almost any common algae  (Hiebert et al., 1979). They are also the prey to many intertidal invertebrates, including carnivorous snails, crabs, or sea stars. Humans are also a major predator of black turban snails, and there is evidence of human collection of these snails as far back as 12,000 years ago (Erlandson et al., 2015). These snails reach sexual maturity at about fourteen millimeters in diameter, and female snails will lay several hundred eggs approximately once per year (Hiebert et al., 1979). Juveniles live under small rocks or in the sand, then as young adults live in the upper intertidal for five to six years before migrating down to the mid/low intertidal. 

## Identification Questions

1) Is the snail surrounded by other similar individuals?

2) Does the snail have four whorls/spirals on its shell?

3) If the snail is wet, does it look black?

\newpage
